### ISSUE TITLE
dSYM Automatic Upload for Unity Build

### ISSUE THREAD

**Issue by finalife** [bugsnag/bugsnag-unity#193]
In the recent days I have been working on my project and also have cloned the bugsnag Unity project. I have followed all of the Unity set up instructions to make sure that errors are being uploaded to Bugsnag. I was notified that with the NDK upload, this must be done with a curl and can't be done automatically with a Unity build at the moment. I am just looking to get confirmation on whether or not dSYMs can be uploaded automatically or do they have to be done with a curl for every new build when it comes to a Unity build? Any information about this is much appreciated.

Thanks a lot,
Christopher

**Comment by mattdyoung** [comment]
@finalife 
We provide a number of methods for automatically or manually uploading dSYMs for iOS apps depending on whether or not you're using Bitcode and whether you're using fastlane or cocoapods (or something else):
https://docs.bugsnag.com/platforms/ios/symbolication-guide/

I'm not aware of any issues with using these methods on the XCode project output from Unity but there are various settings which might affect  this - are you seeing any specific issues?

In general you'd need to follow these instructions if you're using BitCode:
https://docs.bugsnag.com/platforms/ios/symbolication-guide/#with-bitcode
otherwise a post-process step in the Unity build:
https://github.com/bugsnag/bugsnag-unity/blob/master/src/BugsnagUnity/PostProcessBuild.cs
should attempt to automatically add the script shown here to the XCode build:
https://docs.bugsnag.com/platforms/ios/symbolication-guide/#adding-a-build-phase-manually

If you're having issues configuring this correctly please do contact Bugsnag Support with the details via the support link in the Bugsnag dashboard and we'll assist.
