### ISSUE TITLE
Android NDK files not being uploaded

### ISSUE THREAD

**Issue by emrys90** [bugsnag/bugsnag-unity#763]
I followed the documentation here:
https://docs.bugsnag.com/platforms/unity/showing-full-stacktraces/

It's partially working, as after that I do have symbol files uploaded for libOculusXRPlugin.so and libAudioPluginOculusSpatializer.so, but that's all. So it's not uploading the symbols for my own code.

Any ideas why that is? I'm trying to get line numbers to show in the bug reports.

**Comment by clr182** [comment]
Hi @emrys90 

Thank you for reaching out, could you please provide some further details about your issue:
1.  Which version of Unity are you using to build your project?
2. Which guide in our documentation are you following to upload your symbols files?

**Comment by emrys90** [comment]
Version 2020.3.38f1

I used this one:
https://docs.bugsnag.com/platforms/unity/showing-full-stacktraces/#for-projects-using-unity-2019-and-unity-2020

**Comment by clr182** [comment]
Hi @emrys90 

Currently the plugin expects a folder structure at the location indicated by the sharedObjectPath. Each directory should be named by architecture type. Is this path correct for your project? Any .so files within those folders will be searched for debug information, if the .so file does not contain that it will not be uploaded. Some libraries such as libil2cpp.so and libunity.so do not contain debug information so would not be uploaded. Could you tell me which .so files are you trying to upload? Do they contain debug information?

Additionally, in the meantime, it may be worth suggesting that you upload your mapping files manually using the steps in our documentation here: https://docs.bugsnag.com/api/ndk-symbol-mapping-upload/

**Comment by emrys90** [comment]
I don't understand. I don't know what files need to be uploaded. I only followed your tutorial for what needs to be done. All I'm trying to do is have line numbers with the automated bug reports.

**Comment by clr182** [comment]
Hi @emrys90 

In order to symbolicate your Unity frames you must upload the `libunity.so`, `libmain.so` and `libil2cpp.so` files to BugSnag. These files are output to a zip file called `symbols.zip` when the `Create sumbols.zip` option in Player Settings has been set to `Debugging` and you build your application. 

It's worth noting that we have seen some past issues regarding automatically uploading symbol mapping files via the gradle plugin and the version of Unity you are using. While we work on an alternative solution we recommend trying to upload your symbol mapping files manually using the instructions found here https://docs.bugsnag.com/api/ndk-symbol-mapping-upload/legacy/#uploading-symbol-mapping-files

**Comment by mclack** [comment]
Hi @emrys90 

As there hasn't been any activity here for a while, we are now closing this issue.

If you continue to experience any problems, please feel free to reopen this issue, or open a ticket with us directly by contacting support@bugsnag.com.
